# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(408, 98)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.btnUrl = QtWidgets.QPushButton(self.centralwidget)
        self.btnUrl.setObjectName("btnUrl")
        self.gridLayout.addWidget(self.btnUrl, 0, 2, 2, 1)
        self.novoNome = QtWidgets.QLineEdit(self.centralwidget)
        self.novoNome.setObjectName("novoNome")
        self.gridLayout.addWidget(self.novoNome, 1, 1, 1, 1)
        self.inputUrl = QtWidgets.QLineEdit(self.centralwidget)
        self.inputUrl.setText("")
        self.inputUrl.setObjectName("inputUrl")
        self.gridLayout.addWidget(self.inputUrl, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Clonador de Repositórios"))
        self.label.setText(_translate("MainWindow", "Novo Nome"))
        self.label_2.setText(_translate("MainWindow", "Link do Projeto"))
        self.btnUrl.setText(_translate("MainWindow", "Clonar"))
